### ISSUE TITLE
Make 2 usb C hole

### ISSUE THREAD

**Issue by uyaszx** [swill/kad#10]
can i make 2 usb c hole ?

**Comment by swill** [comment]
The USB hole functionality will only let you place one USB hole, but you can create a second hole using the `custom polygon` functionality.  Just make sure to select the `Open Layer` when applying the polygon.

If you have questions, refer to the documentation site: http://builder-docs.swillkb.com/features/#custom-polygons

Let me know if you have any questions...

**Comment by swill** [comment]
Oh, one more thing.  Make sure that you have at least 2 screw holes in the sandwich case between the two holes so the piece between the two holes is held in place in the case.

**Comment by uyaszx** [comment]
ok thx for the info
