### ISSUE TITLE
builder.swillkb.com is down

### ISSUE THREAD

**Issue by aureliengmichaud** [swill/kad#23]
Hi there! The website appears to be down since at least yesterday! Thought I should let you know :)

**Comment by booperlv** [comment]
Once again, the website is down, Hope it can be fixed soon!

**Comment by y-usuzumi** [comment]
Dec 26. Still down.

**Comment by hirin-byte** [comment]
1 January 2021. Still down (sorry for my english)

**Comment by TZKJ2008** [comment]
2 January 2021......

**Comment by nicolemx** [comment]
4 January 2021......

**Comment by swill** [comment]
It is back...
