### ISSUE TITLE
My friend, your website has crashed

### ISSUE THREAD

**Issue by xiaojia998** [swill/kad#32]
My friend, your website has crashed

**Comment by ifohancroft** [comment]
Yeah, it's down again.

I know there are other builders but there are tons of problems with them:

- They can't handle rotated keys
- They can't generate anything other than switch plates
- They simplify the stabilizers
- They can't generate cutouts for Costar based stabilizers
- They can't generate cutouts so you can open the switches without desoldering/removing them

There is nothing like your website currently (that I know of).

**Comment by swill** [comment]
I am moving the site and DNS propagation may make the site down for the next 12 hours.  It will be back.  I have also fixed a number of issues that I introduced in the custom polygon cutting.  So that will be fixed when it comes back.
